sn*dup(sn*head)
{
    sn*p1=head,*p2;
    if(p1==NULL||p1->next==NULL)
    {
        return head;
    }
    else
    {
        p2=p1;
        p1=p1->next;
        while(p1!=NULL)
        {
            if(p2->info==p1->info)
            {
                sn*temp;
                temp=p1;
                p2->next=p1->next;
                p1=p1->next;
                free(temp);
            }
            else
            {
                p2=p1;
                p1=p1->next;
            }
        }
        return head;
    }
}